spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tecnopracticas?useSSL=false&serverTimezone=America/Bogota
    username: usertecnopracticas
    password: tecnopracticas
  cloud:
    openfeign:
      client:
        config:
          mensajeriaClient:
            read-timeout: 600
  jpa:
    generate-ddl: false
    open-in-view: true

  jackson:
    time-zone: America/Bogota

  basic:
    enabled: true
  threads:
    virtual:
      enabled: true

server:
<<<<<<< HEAD
  port: 10451
=======
  port: 10453
>>>>>>> a19ca288ca89986a7c55ea541e529da97054fa95

