spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tecnopracticas?useSSL=false&serverTimezone=America/Bogota
    username: usertecnopracticas
    password: tecnopracticas
  jpa:
    generate-ddl: false
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: practicastecnologicocomfenalco@gmail.com
    password: qzeeegjimzbiscyj
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
          
  jackson:
    time-zone: America/Bogota
  
server:
  port: 10455 

tecnopracticas:
  urls:
   verificacion: http://127.0.0.1:5501/resources/templates/Formularios/verificacion/verificacionC.html
   restablecer-clave: http://127.0.0.1:5501/resources/templates/Restablecerp/ResPassword.html
   logo: https://raw.githubusercontent.com/JeysonM11/plantilla_correos/main/logos/LOGO_NUEVO.png
