
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/tecnopracticas?useSSL=false&serverTimezone=America/Bogota
      username: usertecnopracticas
      password: tecnopracticas
    cloud:
      openfeign:
        client:
          config:
            mensajeriaClient:
             read-timeout: 600
    jpa:
      generate-ddl: false
      open-in-view: true

    jackson:
      time-zone: America/Bogota

    basic:
        enabled: true
    threads:
      virtual:
        enabled: true

  server:
    port: 10451




spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tecnopracticas?useSSL=false&serverTimezone=America/Bogota
    username: usertecnopracticas
    password: tecnopracticas
  cloud:
    openfeign:
      client:
        config:
          mensajeriaClient:
           read-timeout: 100
    gcp:
     credentials:
      location: classpath:/tecnopracticas-f8672c420e5b.json
     project-id: tecnopracticas
  jpa:
    generate-ddl: false
    open-in-view: true

  jackson:
    time-zone: America/Bogota
 
  servlet:
    multipart:
      max-file-size: 5MB
          
  threads:
    virtual:
      enabled: true

tecnopracticas:
  gcp:
   project_id: tecnopracticas
   credentials: tecnopracticas-f8672c420e5b.json
  paths:
   cvs: curriculums
   ruta_cv: ${gcs-resource-test-bucket}/${tecnopracticas.paths.cvs}
gcs-resource-test-bucket: tecnopracticas-resources


server:
  port: 10451

